#!/bin/bash

# when run on my sexy slim macbook
if [ $(uname -s) == 'Darwin' ]
then
    alias bilai='/Applications/Banglalion_Connection_Manager.app/Contents/MacOS/WiMAXDevDetector'
    alias keepassx='open /Applications/KeePassX.app'
    alias nosleep='pmset noidle'
    alias brin='brew install'
    alias brud='brew update'
    alias brug='brew upgrade'
    alias brcl='brew cleanup'
    alias brcu='brew cask update'
    alias swl='sudo softwareupdate -l'
    alias swu='sudo softwareupdate -via'
fi

# pbcopy and pbpaste for linux
if [ $(uname -s) == 'Linux' ]
then
    alias pbcopy='xclip -selection clipboard'
    alias pbpaste='xclip -selection clipboard -o'
fi

# allow aliases to be run after sudo
alias sudo='sudo '

# cd to directory
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../../'
alias ~='cd ~'

# list cmd
alias ls="ls --color=auto -pG"
alias l='ls -1'
alias ll='ls -alF'
alias la='ls -1A'
alias lh='ls -lh'
alias lr="ls -1t"

# coreutils
alias chmodx="chmod +x"

# file and dir utils
alias md='mkdir -p'
alias ex='extract'
alias f='file'
alias ups="ps -u $USER -o pid,%cpu,%mem,start,time,bsdtime,command"
alias cpd="cp -r"
alias realpath="readlink -f"

# grep color
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# find command
alias ff='find . -type f -iname'
alias fd='find . -type d -iname'
alias fe='find . -type f -executable -iname'
ffmin() { find . -type f -size +$1; }
ffmax() { find . -type f -size -$1; }
alias duh='du -hs'
alias dub='du -b'

# password generators
alias pe='apg -a1 -m 16 -M NCL'
alias ph='apg -a1 -m 16 -M NCLS'

# terminal
alias c='clear'
alias q='exit'

# docker
alias dockerlast='docker start -a -i `docker ps -q -l`'

# make
alias mk='make'
alias mk4='make -j4'
alias mk8='make -j8'
alias mkc='make clean'
alias mkv='make V=s'
alias mkm='make menuconfig'

# interpreters
alias py='python'
alias py2='python'
alias py3='python3'
alias rb='ruby'
alias pl='perl'

# downloaders
alias dl='wget'
alias yd='youtube-dl --prefer-ffmpeg'
alias ffmpeg='ffmpeg -hide_banner'
alias ffinfo='ffprobe -hide_banner'

# network
alias s='ssh'
alias t='telnet'
alias sv='ssh -v'
alias sshk='killall ssh'
alias sshf='rm -f ~/.ssh/known_hosts'
alias nets="netstat -plutn"

# text converter
alias lower="tr 'A-Z' 'a-z'"
alias upper="tr 'a-z' 'A-Z'"
alias nospace="tr -d ' '"
alias title="sed 's/[^ ]\+/\L\u&/g'"

# git
alias ga='git add'
alias gb='git branch'
alias gc='git commit -m'
alias gd='git diff'
alias gck='git checkout'
alias gcl='git clone'
alias gcpk='git cherry-pick'
alias gf='git fetch'
alias gi='git init'
alias gl='git log --pretty=oneline'
alias gm='git merge'
alias gpl='git pull'
alias gps='git push'
alias gs='git status'
alias gcls="git clone -b master --single-branch --depth 1"
alias gundo="git reset HEAD~"

# cd to directory
alias work='cd /work'
alias mtk='cd /work/mtk/RT288x_SDK/source'
alias tftp='cd /work/archive/tftpd'
alias http='cd /work/http'

# others
alias now='date +%Y-%m-%d\ %H:%M:%S'

# codeblocks clean
# alias cbc='rm -rf bin obj *.depend *.layout'

# dd with progress report
alias dd='dcfldd'
alias rsync='rsync -rltuDv'
alias rsyncdotdel='rsync -rltDuv --exclude ".*" --delete'

# jekyll
# alias js='jekyll serve --watch --incremental --trace'
# alias jc='jekyll clean'
# alias jb='jekyll build'

# apt
alias au='apt update'
alias ai='apt install'
alias adu='apt dist-update'
alias ac='apt clean'
alias aac='apt autoclean'
alias aar='apt autoremove'

# face
alias face='cp ~/.face ~/face.png'
alias facerm='rm -f ~/face.png'

# sct
alias cool='sct 6500'
alias warm='sct 3400'

# turn off display
alias doff='xset dpms force off'
alias coffee='qdbus org.freedesktop.ScreenSaver /ScreenSaver Lock; xset dpms force off'

# adb
alias adba="adb shell 'pm list packages -3' | sed -e 's/^package://' | sort"
alias adbd='adb devices'
alias adbs='adb shell'
logcat() { adb logcat --pid $(adb shell ps | grep "$1" | awk '{print $2}'); }

# network
alias dig='dig +noall +answer'
alias p='ping'
alias ns='nslookup'

#alias title='qdbus org.kde.konsole $KONSOLE_DBUS_SESSION setTitle 1'

alias qmake5='/home/minhaz/.Qt5.7.0/5.7/gcc_64/bin/qmake'
alias lua='/usr/bin/lua5.1'

# mosquitto
alias pub="mosquitto_pub"
alias sub="mosquitto_sub -v"

# peer list
alias peersip='arp-scan 192.168.11.0/24 -Ieno1 | tail -n +3 | head -n -3 | awk "{print \$1,\$2}" | sort -k 1 --version-sort'
alias peersmac='arp-scan 192.168.11.0/24 -Ieno1 | tail -n +3 | head -n -3 | awk "{print \$2,\$1}" | sort -k 1 --version-sort'

# namaz alert
namaz() { sleep $1 && kdialog --msgbox "Namaz!!!"; }

# serial
alias uart1152="picocom -b115200 /dev/ttyUSB0"
alias uart5760="picocom -b57600 /dev/ttyUSB0"

# other applications
alias teamviewerd="/opt/teamviewer/tv_bin/teamviewerd"