#!/bin/bash

# when run on my sexy slim macbook
if [ $(uname -s) == 'Darwin' ]
then
    alias bilai='/Applications/Banglalion_Connection_Manager.app/Contents/MacOS/WiMAXDevDetector'
    alias keepassx='open /Applications/KeePassX.app'
    alias nosleep='pmset noidle'
    alias brin='brew install'
    alias brud='brew update'
    alias brug='brew upgrade'
    alias brcl='brew cleanup'
    alias brcu='brew cask update'
    alias swl='sudo softwareupdate -l'
    alias swu='sudo softwareupdate -via'
fi

# pbcopy and pbpaste for linux
if [ $(uname -s) == 'Linux' ]
then
    alias pbcopy='xclip -selection clipboard'
    alias pbpaste='xclip -selection clipboard -o'
fi

# allow aliases to be run after sudo
alias sudo='sudo '

# cd to directory
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../../'
alias ~='cd ~'

# list cmd
alias ls="ls --color=auto -pG"
alias l='ls -1'
alias ll='ls -alF'
alias la='ls -1A'
alias lh='ls -lh'

# file and dir utils
alias md='mkdir -p'
alias ex='extract'
alias f='file'
alias ups="ps -u $USER -o pid,%cpu,%mem,start,time,bsdtime,command"

# grep color
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# find command
alias ff='find . -type f -iname'
alias fd='find . -type d -iname'
alias fe='find . -type f -executable -iname'
alias duh='du -hs'

# password generators
alias pe='apg -a1 -m 16 -M NCL'
alias ph='apg -a1 -m 16 -M NCLS'

# terminal
alias c='clear'
alias q='exit'

# make
alias mk='make'
alias mk4='make -j4'
alias mk8='make -j8'
alias mkc='make clean'
alias mkv='make V=s'
alias mkm='make menuconfig'

# interpreters
alias py='python'
alias py3='python3'
alias rb='ruby'
alias pl='perl'

# downloaders
alias dl='wget'
alias yd='youtube-dl --prefer-ffmpeg'
alias ffmpeg='ffmpeg -hide_banner'
alias ffinfo='ffprobe -hide_banner'

# ssh
alias s='ssh'
alias sv='ssh -v'
alias sshk='killall ssh'
alias sshf='rm -f ~/.ssh/known_hosts'

# text converter
alias lower="tr 'A-Z' 'a-z'"
alias upper="tr 'a-z' 'A-Z'"
alias nospace="tr -d ' '"

# git
alias ga='git add'
alias gb='git branch'
alias gc='git commit -m'
alias gck='git checkout'
alias gcl='git clone'
alias gcpk='git cherry-pick'
alias gf='git fetch'
alias gi='git init'
alias gl='git log --pretty=oneline'
alias gm='git merge'
alias gpl='git pull'
alias gps='git push'
alias gs='git status'

# cd to directory
# alias data='cd /media/data'
alias work='cd /work'

# others
alias now='date +%Y-%m-%d\ %H:%M:%S'

# codeblocks clean
# alias cbc='rm -rf bin obj *.depend *.layout'

# dd with progress report
alias dd='dcfldd'
alias rsync='rsync -rltuDv'

# jekyll
# alias js='jekyll serve --watch --incremental --trace'
# alias jc='jekyll clean'
# alias jb='jekyll build'

# apt
alias au='apt update'
alias ai='apt install'
alias adu='apt dist-update'
alias ac='apt clean'
alias aac='apt autoclean'
alias aar='apt autoremove'

# face
alias face='cp ~/.face ~/face.png'
alias facerm='rm -f ~/face.png'

# sct
alias cool='sct 6500'
alias warm='sct 3400'

# turn off display
alias doff='xset dpms force off'
alias coffee='qdbus org.freedesktop.ScreenSaver /ScreenSaver Lock; xset dpms force off'

# adb
alias adba="adb shell 'pm list packages -3' | sed -e 's/^package://' | sort"
alias adbd='adb devices'
alias adbs='adb shell'

# network
alias dig='dig +noall +answer'
alias p='ping'
alias ns='nslookup'

alias title='qdbus org.kde.konsole $KONSOLE_DBUS_SESSION setTitle 1'

alias qmake5='/home/minhaz/.Qt5.7.0/5.7/gcc_64/bin/qmake'
alias lua='/usr/bin/lua5.1'

# mosquitto
alias pub="mosquitto_pub -v"
alias sub="mosquitto_sub -v"
