#!/bin/bash

# Author: Md. Minhazul Haque <mdminhazulhaque@gmail.com>

alias teamviewerd="/opt/teamviewer/tv_bin/teamviewerd"
alias nginxd="mkdir -p /var/log/nginx && nginx"
alias brokerstat="/work/repo/apl.tools/brokerstat/brokerstat"
alias subd="/work/repo/apl.tools/subd/subd"
alias shviz="/work/repo/apl.tools/shviz/shviz"
alias rmgmt="/work/repo/apl.tools/rmgmt/rmgmt"
alias wasactl="/work/repo/apl.tools/wasactl/app.py" 
alias wasalive="/work/repo/apl.tools/wasactl/live.py" 
alias eclipse-oh2="/work/eclipse-openhab2/openhab2-master/eclipse/eclipse"
