#!/bin/bash

alias work='cd /work'
alias repo='cd /work/repo'
alias cpp='cd /work/repo/router-cpp'
alias www='cd /work/repo/router-www'
alias mtk='cd /work/mtk/RT288x_SDK/source'
alias ui='cd /work/repo/gridpal.ui'
alias bindings='cd /work/repo/gridpal.bindings'
# alias tftp='cd /work/archive/tftpd'
# alias http='cd /work/http'

# openhab
alias oaddons='cd /usr/share/openhab2/addons'
alias oh='cd /etc/openhab2'
alias ohrestart='systemctl restart openhab2'
alias ohstart='systemctl start openhab2'
alias ohstop='systemctl stop openhab2'
alias ohlogs='openhab-cli showlogs'